# Generated by Django 5.1.1 on 2024-11-28 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_post_catogery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Catogery',
            new_name='Category',
        ),
    ]
