# Generated by Django 5.1.1 on 2024-11-28 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_rename_catogery_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Category',
        ),
    ]
