# Generated by Django 5.1.1 on 2024-12-03 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Category',
        ),
    ]
